__author__ = 'xiefei'
import sys
import time
import  datetime
import binascii


stu = {
    'IDT_TT':   'TT'     ,
    'IDT_ST'     :   'ST'  ,
    'IDT_RGZS'   :	'RGZS' 	,
    'IDT_PIC'   :	'PIC' 	,
    'IDT_DRP'   :	'DRP' 	,
    'IDT_DRZ1'   :	'DRZ1' 	,
    'IDT_DRZ2'   :	'DRZ2' 	,
    'IDT_DRZ3'   :	'DRZ3' 	,
    'IDT_DRZ4'   :	'DRZ4' 	,
    'IDT_DRZ5'   :	'DRZ5' 	,
    'IDT_DRZ6'   :	'DRZ6' 	,
    'IDT_DRZ7'   :	'DRZ7' 	,
    'IDT_DRZ8'   :	'DRZ8' 	,
    'IDT_DATA'   :	'DATA' 	,
    'IDT_AC'   :	'AC' 	,
    'IDT_AI'   :	'AI' 	,
    'IDT_C'   :	    'C' 	,
    'IDT_DRxnn'   :	'DRxnn' ,
    'IDT_DT'   :	'DT' 	,
    'IDT_ED'   :	'ED' 	,
    'IDT_EJ'   :	'EJ' 	,
    'IDT_FL'   :	'FL' 	,
    'IDT_GH'   :	'GH' 	,
    'IDT_GN'   :	'GN' 	,
    'IDT_GS'   :	'GS' 	,
    'IDT_GT'   :	'GT' 	,
    'IDT_GTP'   :	'GTP' 	,
    'IDT_H'     :	'H' 	,
    'IDT_HW'    :	'HW' 	,
    'IDT_M10'   :	'M10' 	,
    'IDT_M20'   :	'M20' 	,
    'IDT_M30'   :	'M30' 	,
    'IDT_M40'   :	'M40' 	,
    'IDT_M50'   :	'M50' 	,
    'IDT_M60'   :	'M60' 	,
    'IDT_M80'   :	'M80' 	,
    'IDT_M100'  :	'M100' 	,
    'IDT_MST'   :	'MST' 	,
    'IDT_NS'    :	'NS' 	,
    'IDT_P1'    :	'P1' 	,
    'IDT_P2'    :	'P2' 	,
    'IDT_P3'    :	'P3' 	,
    'IDT_P6'    :	'P6' 	,
    'IDT_P12'   :	'P12' 	,
    'IDT_PD'    :	'PD' 	,
    'IDT_PJ'    :	'PJ' 	,
    'IDT_PN01'  :	'PN01' 	,
    'IDT_PN05'  :	'PN05' 	,
    'IDT_PN10'  :	'PN10' 	,
    'IDT_PN30'  :	'PN30' 	,
    'IDT_PR'   :	'PR' 	,
    'IDT_PT'   :	'PT' 	,
    'IDT_Q '   :	'Q' 	,
    'IDT_Q1'   :	'Q1' 	,
    'IDT_Q2'   :	'Q2' 	,
    'IDT_Q3'   :	'Q3' 	,
    'IDT_Q4'   :	'Q4' 	,
    'IDT_Q5'   :	'Q5' 	,
    'IDT_Q6'   :	'Q6' 	,
    'IDT_Q7'   :	'Q7' 	,
    'IDT_Q8'   :	'Q8' 	,
    'IDT_QA'   :	'QA' 	,
    'IDT_QZ'   :	'QZ' 	,
    'IDT_SW'   :	'SW' 	,
    'IDT_UC'   :	'UC' 	,
    'IDT_UE'   :	'UE' 	,
    'IDT_US'   :	'US' 	,
    'IDT_VA'   :	'VA' 	,
    'IDT_VJ'   :	'VJ' 	,
    'IDT_VT'   :	'VT' 	,
    'IDT_Z'    :	'Z' 	,
    'IDT_ZB'   :	'ZB' 	,
    'IDT_ZU'   :	'ZU' 	,
    'IDT_Z1'   :	'Z1' 	,
    'IDT_Z2'   :	'Z2' 	,
    'IDT_Z3'   :	'Z3' 	,
    'IDT_Z4'   :	'Z4' 	,
    'IDT_Z5'   :	'Z5' 	,
    'IDT_Z6'   :	'Z6' 	,
    'IDT_Z7'   :	'Z7' 	,
    'IDT_Z8'   :	'Z8' 	,
    'IDT_SQ'   :	'SQ' 	,
    'IDT_ZT'   :	'ZT' 	,
    'IDT_pH'   :	'pH' 	,
    'IDT_DO'   :	'DO' 	,
    'IDT_COND'   :	'COND' 	,
    'IDT_TURB'   :	'TURB' 	,
    'IDT_CODMN'  :	'CODMN' ,
    'IDT_REDOX'  :	'REDOX' ,
    'IDT_NH4N'   :	'NH4N' 	,
    'IDT_TP'   :	'TP' 	,
    'IDT_TN'   :	'TN' 	,
    'IDT_TOC'  :	'TOC' 	,
    'IDT_CU'   :	'CU' 	,
    'IDT_ZN'   :	'ZN' 	,
    'IDT_SE'   :	'SE' 	,
    'IDT_AS'   :	'AS' 	,
    'IDT_THG'  :	'THG' 	,
    'IDT_CD'   :	'CD' 	,
    'IDT_PB'   :	'PB' 	,
    'IDT_CHLA'  :	'CHLA' 	,
    'IDT_WP1'   :	'WP1' 	,
    'IDT_WP2'   :	'WP2' 	,
    'IDT_WP3'   :	'WP3' 	,
    'IDT_WP4'   :	'WP4' 	,
    'IDT_WP5'   :	'WP5' 	,
    'IDT_WP6'   :	'WP6' 	,
    'IDT_WP7'   :	'WP7' 	,
    'IDT_WP8'   :	'WP8' 	,
    'IDT_SYL1'   :	'SYL1' 	,
    'IDT_SYL2'   :	'SYL2' 	,
    'IDT_SYL3'   :	'SYL3' 	,
    'IDT_SYL4'   :	'SYL4' 	,
    'IDT_SYL5'   :	'SYL5' 	,
    'IDT_SYL6'   :	'SYL6' 	,
    'IDT_SYL7'   :	'SYL7' 	,
    'IDT_SYL8'   :	'SYL8' 	,
    'IDT_SBL1'   :	'SBL1' 	,
    'IDT_SBL2'   :	'SBL2' 	,
    'IDT_SBL3'   :	'SBL3' 	,
    'IDT_SBL4'   :	'SBL4' 	,
    'IDT_SBL5'   :	'SBL5' 	,
    'IDT_SBL6'   :	'SBL6' 	,
    'IDT_SBL7'   :	'SBL7' 	,
    'IDT_SBL8'   :	'SBL8' 	,
    'IDT_VTA'   :	'VTA' 	,
    'IDT_VTB'   :	'VTB' 	,
    'IDT_VTC'   :	'VTC' 	,
    'IDT_VIA'   :	'VIA' 	,
    'IDT_VIB'   :	'VIB' 	,
    'IDT_VIC'   :	'VIC' 	,
}
class messag ():

    def getSystimeS(self):
        return time.strftime("%y%m%d%H%M%S")

    def getSystime(self):
        return time.strftime("%y%m%d%H%M")



    def sendRtuArgTable(self, data, Len):
        print(str(data))
        print(stu.get('IDT_VIC'))

    def initRtu(self):
        self.sendRtuArgTable(self,'nihao' , 5)



