# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rtuUI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1005, 841)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(56, 10, 71, 213))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout.addWidget(self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout.addWidget(self.comboBox_5)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(380, 0, 591, 591))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_8.setGeometry(QtCore.QRect(0, 0, 381, 551))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(1)
        self.tableWidget_8.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setItem(2, 0, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 0, 381, 551))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(1)
        self.tableWidget_7.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(3, 0, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox_RtuType = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_RtuType.setGeometry(QtCore.QRect(90, 10, 81, 21))
        self.comboBox_RtuType.setObjectName("comboBox_RtuType")
        self.lineEdit_cenAdd = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_cenAdd.setGeometry(QtCore.QRect(90, 49, 81, 21))
        self.lineEdit_cenAdd.setObjectName("lineEdit_cenAdd")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 12, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 91, 16))
        font = QtGui.QFont()
        font.setFamily("04b_21")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(0, 670, 101, 16))
        self.checkBox.setObjectName("checkBox")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(0, 690, 761, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 360, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(380, 610, 171, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.layoutWidget.raise_()
        self.tabWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.checkBox.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.textBrowser.raise_()
        self.tableWidget.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        self.pushButton.clicked.connect(Form.check_port)
        self.pushButton_2.clicked.connect(Form.open_port)
        self.pushButton_3.clicked.connect(Form.close_port)
        self.pushButton_5.clicked.connect(Form.write_rtu)
        self.pushButton_4.clicked.connect(Form.read_rtu)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "易周科技 YZ-G300"))
        self.comboBox.setItemText(0, _translate("Form", "COM1"))
        self.comboBox.setItemText(1, _translate("Form", "COM2"))
        self.comboBox.setItemText(2, _translate("Form", "COM3"))
        self.comboBox.setItemText(3, _translate("Form", "COM4"))
        self.comboBox.setItemText(4, _translate("Form", "COM5"))
        self.comboBox.setItemText(5, _translate("Form", "COM6"))
        self.comboBox.setItemText(6, _translate("Form", "COM7"))
        self.comboBox.setItemText(7, _translate("Form", "COM8"))
        self.comboBox.setItemText(8, _translate("Form", "COM9"))
        self.comboBox.setItemText(9, _translate("Form", "COM10"))
        self.comboBox_2.setItemText(0, _translate("Form", "1200"))
        self.comboBox_2.setItemText(1, _translate("Form", "2400"))
        self.comboBox_2.setItemText(2, _translate("Form", "4800"))
        self.comboBox_2.setItemText(3, _translate("Form", "9600"))
        self.comboBox_2.setItemText(4, _translate("Form", "14400"))
        self.comboBox_2.setItemText(5, _translate("Form", "19200"))
        self.comboBox_2.setItemText(6, _translate("Form", "34800"))
        self.comboBox_2.setItemText(7, _translate("Form", "43000"))
        self.comboBox_2.setItemText(8, _translate("Form", "57600"))
        self.comboBox_2.setItemText(9, _translate("Form", "76800"))
        self.comboBox_2.setItemText(10, _translate("Form", "115200"))
        self.comboBox_3.setItemText(0, _translate("Form", "1"))
        self.comboBox_3.setItemText(1, _translate("Form", "0"))
        self.comboBox_4.setItemText(0, _translate("Form", "8"))
        self.comboBox_4.setItemText(1, _translate("Form", "7"))
        self.comboBox_4.setItemText(2, _translate("Form", "6"))
        self.comboBox_4.setItemText(3, _translate("Form", "5"))
        self.comboBox_5.setItemText(0, _translate("Form", "无"))
        self.comboBox_5.setItemText(1, _translate("Form", "奇"))
        self.comboBox_5.setItemText(2, _translate("Form", "偶"))
        self.pushButton.setText(_translate("Form", "串口检测"))
        self.pushButton_2.setText(_translate("Form", "打开串口"))
        self.pushButton_3.setText(_translate("Form", "关闭串口"))
        item = self.tableWidget_8.verticalHeaderItem(0)
        item.setText(_translate("Form", "休眠延时"))
        item = self.tableWidget_8.verticalHeaderItem(1)
        item.setText(_translate("Form", "LCD关闭延时"))
        item = self.tableWidget_8.verticalHeaderItem(2)
        item.setText(_translate("Form", "LCD_背光延时"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("Form", "值"))
        __sortingEnabled = self.tableWidget_8.isSortingEnabled()
        self.tableWidget_8.setSortingEnabled(False)
        item = self.tableWidget_8.item(0, 0)
        item.setText(_translate("Form", "9600"))
        item = self.tableWidget_8.item(1, 0)
        item.setText(_translate("Form", "9600"))
        item = self.tableWidget_8.item(2, 0)
        item.setText(_translate("Form", "9600"))
        self.tableWidget_8.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "系统参数"))
        item = self.tableWidget_7.verticalHeaderItem(0)
        item.setText(_translate("Form", "BAUD_232_PORT1"))
        item = self.tableWidget_7.verticalHeaderItem(1)
        item.setText(_translate("Form", "BAUD_232_PORT2"))
        item = self.tableWidget_7.verticalHeaderItem(2)
        item.setText(_translate("Form", "BAUD_485_PORT1"))
        item = self.tableWidget_7.verticalHeaderItem(3)
        item.setText(_translate("Form", "BAUD_458_PORT2"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("Form", "值"))
        __sortingEnabled = self.tableWidget_7.isSortingEnabled()
        self.tableWidget_7.setSortingEnabled(False)
        item = self.tableWidget_7.item(0, 0)
        item.setText(_translate("Form", "9600"))
        item = self.tableWidget_7.item(1, 0)
        item.setText(_translate("Form", "9600"))
        item = self.tableWidget_7.item(2, 0)
        item.setText(_translate("Form", "9600"))
        item = self.tableWidget_7.item(3, 0)
        item.setText(_translate("Form", "9600"))
        self.tableWidget_7.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "通信设置"))
        self.label_3.setText(_translate("Form", "测站类型"))
        self.label_4.setText(_translate("Form", "中心站地址"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "发报设置"))
        self.checkBox.setText(_translate("Form", "十六进制显示"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "a"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "v"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "2"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "已关闭"))
        self.pushButton_4.setText(_translate("Form", "读取参数"))
        self.pushButton_5.setText(_translate("Form", "写入参数"))

