# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rtuUI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(961, 869)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 601, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_5)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.tabWidget_3 = QtWidgets.QTabWidget(Form)
        self.tabWidget_3.setGeometry(QtCore.QRect(640, 30, 261, 771))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_1.setGeometry(QtCore.QRect(0, 0, 261, 741))
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(1)
        self.tableWidget_1.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(2, 0, item)
        self.tabWidget_3.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 251, 781))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 10, 381, 771))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.tab_2)
        self.verticalScrollBar.setGeometry(QtCore.QRect(240, 0, 16, 751))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.tabWidget_3.addTab(self.tab_2, "")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.checkBox.setObjectName("checkBox")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 100, 601, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(640, 810, 248, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 840, 541, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(20, 470, 601, 51))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 450, 54, 12))
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 530, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.checkBox.raise_()
        self.textBrowser.raise_()
        self.tabWidget_3.raise_()
        self.label_2.raise_()
        self.textEdit.raise_()
        self.label_3.raise_()
        self.pushButton_6.raise_()

        self.retranslateUi(Form)
        self.tabWidget_3.setCurrentIndex(2)
        self.pushButton.clicked.connect(Form.check_port)
        self.pushButton_2.clicked.connect(Form.open_port)
        self.pushButton_3.clicked.connect(Form.close_port)
        self.pushButton_5.clicked.connect(Form.write_rtu)
        self.pushButton_4.clicked.connect(Form.read_rtu)
        self.verticalScrollBar.sliderMoved['int'].connect(Form.moveTable)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "易周科技 YZ-G300"))
        self.pushButton.setText(_translate("Form", "串口检测"))
        self.comboBox.setItemText(0, _translate("Form", "COM1"))
        self.comboBox.setItemText(1, _translate("Form", "COM2"))
        self.comboBox.setItemText(2, _translate("Form", "COM3"))
        self.comboBox.setItemText(3, _translate("Form", "COM4"))
        self.comboBox.setItemText(4, _translate("Form", "COM5"))
        self.comboBox.setItemText(5, _translate("Form", "COM6"))
        self.comboBox.setItemText(6, _translate("Form", "COM7"))
        self.comboBox.setItemText(7, _translate("Form", "COM8"))
        self.comboBox.setItemText(8, _translate("Form", "COM9"))
        self.comboBox.setItemText(9, _translate("Form", "COM10"))
        self.comboBox_2.setItemText(0, _translate("Form", "1200"))
        self.comboBox_2.setItemText(1, _translate("Form", "2400"))
        self.comboBox_2.setItemText(2, _translate("Form", "4800"))
        self.comboBox_2.setItemText(3, _translate("Form", "9600"))
        self.comboBox_2.setItemText(4, _translate("Form", "14400"))
        self.comboBox_2.setItemText(5, _translate("Form", "19200"))
        self.comboBox_2.setItemText(6, _translate("Form", "34800"))
        self.comboBox_2.setItemText(7, _translate("Form", "43000"))
        self.comboBox_2.setItemText(8, _translate("Form", "57600"))
        self.comboBox_2.setItemText(9, _translate("Form", "76800"))
        self.comboBox_2.setItemText(10, _translate("Form", "115200"))
        self.comboBox_5.setItemText(0, _translate("Form", "无"))
        self.comboBox_5.setItemText(1, _translate("Form", "奇"))
        self.comboBox_5.setItemText(2, _translate("Form", "偶"))
        self.comboBox_4.setItemText(0, _translate("Form", "8"))
        self.comboBox_4.setItemText(1, _translate("Form", "7"))
        self.comboBox_4.setItemText(2, _translate("Form", "6"))
        self.comboBox_4.setItemText(3, _translate("Form", "5"))
        self.comboBox_3.setItemText(0, _translate("Form", "1"))
        self.comboBox_3.setItemText(1, _translate("Form", "0"))
        self.pushButton_2.setText(_translate("Form", "打开串口"))
        self.pushButton_3.setText(_translate("Form", "关闭串口"))
        self.label.setText(_translate("Form", "已关闭"))
        item = self.tableWidget_1.verticalHeaderItem(0)
        item.setText(_translate("Form", "休眠延时"))
        item = self.tableWidget_1.verticalHeaderItem(1)
        item.setText(_translate("Form", "LCD关闭延时"))
        item = self.tableWidget_1.verticalHeaderItem(2)
        item.setText(_translate("Form", "LCD_背光延时"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "值"))
        __sortingEnabled = self.tableWidget_1.isSortingEnabled()
        self.tableWidget_1.setSortingEnabled(False)
        item = self.tableWidget_1.item(0, 0)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_1.item(1, 0)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_1.item(2, 0)
        item.setText(_translate("Form", "1"))
        self.tableWidget_1.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("Form", "系统参数"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "BAUD_232_PORT1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "BAUD_232_PORT2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "BAUD_485_PORT1"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "BAUD_458_PORT2"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "值"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Form", "9600"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Form", "9600"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Form", "9600"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Form", "9600"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("Form", "通信设置"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Form", "中心站地址"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Form", "测站地址"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Form", "测站类型"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Form", "密码"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "值"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("Form", "01"))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("Form", "01010101"))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("Form", "1234"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("Form", "发报设置"))
        self.checkBox.setText(_translate("Form", "十六进制显示"))
        self.pushButton_5.setText(_translate("Form", "写入参数"))
        self.pushButton_4.setText(_translate("Form", "读取参数"))
        self.label_2.setText(_translate("Form", "N/A"))
        self.label_3.setText(_translate("Form", "HEX路径"))
        self.pushButton_6.setText(_translate("Form", "更新RTU"))

